version: "3"

services:

  api-vertem:
    image: registry.digitalocean.com/dcr-samuel/vertem-news-api:${TAG}
    container_name: vertem-news-api
    build: 
      context: Vertem.News
      dockerfile: ./Vertem.News.Api/Dockerfile
      args:
        - TAG=${TAG}
    ports:
      - "5008:5008"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5008
    depends_on:
      - cache-vertem
    networks:
      - rede-vertem
      
  cache-vertem:
    image: redis:alpine
    container_name: vertem-news-redis
    restart: always
    ports:
      - '5009:5009'
    networks:
      - rede-vertem
      
networks:
  rede-vertem:
    driver: bridge