version: "3"

services:

  api-vertem:
    image: registry.digitalocean.com/dcr-samuel/vertem-news-api:${TAG}
    container_name: vertem-news-api
    build: 
      context: Vertem.News
      dockerfile: ./Vertem.News.Api/Dockerfile
      args:
        - TAG=${TAG}
    ports:
      - "5008:5008"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5008
    depends_on:
      - cache-vertem
      - log-vertem
    networks:
      - rede-vertem
      
  cache-vertem:
    image: redis:alpine
    container_name: vertem-news-redis
    restart: always
    ports:
      - "5010:6379"
    networks:
      - rede-vertem
      
  log-vertem:
    image: datalust/seq:latest
    container_name: vertem-news-seq
    ports:
      - "5012:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_ADMIN_PASSWORD=admin
    networks:
      - rede-vertem
      
  db-vertem:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: vertem-news-sql-server
    environment:
      SA_PASSWORD: "##$%&*123456"
      ACCEPT_EULA: "Y"
    ports:
      - "5014:1433"
    depends_on:
      - log-vertem
    volumes:
      - vol-data-vertem:/var/opt/mssql
    networks:
      - rede-vertem
      
networks:
  rede-vertem:
    driver: bridge
    
volumes:
  vol-data-vertem:
    driver: local