version: "3"

services:

  api-vertem:
    image: registry.digitalocean.com/dcr-samuel/vertem-news-api:${TAG}
    container_name: vertem-news-api
    build: 
      context: Vertem.News
      dockerfile: ./Vertem.News.Api/Dockerfile
      args:
        - TAG=${TAG}
    ports:
      - "5008:5008"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5008
    depends_on:
      - cache-vertem
      - log-vertem
    networks:
      - rede-vertem
      
  cache-vertem:
    image: redis:alpine
    container_name: vertem-news-redis
    restart: always
    ports:
      - "5010:6379"
    networks:
      - rede-vertem
      
  log-vertem:
    image: datalust/seq:latest
    container_name: vertem-news-seq
    ports:
      - "5012:5341"
      - "5013:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_LICENSE=free
    networks:
      - rede-vertem
      
  db-vertem:
    image: postgres:latest
    container_name: vertem-news-postgres
    environment:
      - POSTGRES_USER=sequser
      - POSTGRES_PASSWORD=seqpassword
      - POSTGRES_DB=seqdb
    ports:
      - "5014:5432"
    depends_on:
      - log-vertem
    volumes:
      - vol-data-vertem:/var/lib/postgresql/data
    networks:
      - rede-vertem
      
networks:
  rede-vertem:
    driver: bridge
    
volumes:
  vol-data-vertem:
    driver: local